### ISSUE TITLE
unpin `pydata-sphinx-theme==0.15.2`

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone-sphinx-theme#42]
When https://github.com/executablebooks/sphinx-book-theme/issues/865 is resolved, repin dependencies to latest in `pyproject.toml`.

```toml
dependencies = [
  # stable pins, see https://github.com/plone/plone-sphinx-theme/issues/42
  "myst-parser==3.0.1",
  "pydata-sphinx-theme==0.15.4",
  "sphinx==7.3.7",
  "sphinx-book-theme==1.1.3",
]
```

Upstream of Sphinx Book Theme, this is the issue to watch: https://github.com/pydata/pydata-sphinx-theme/issues/2067
