### ISSUE TITLE
Indicate external links with an external link icon

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone-sphinx-theme#53]
Consider adding an indicator for external links with an external link icon.

### Current

![Image](https://github.com/user-attachments/assets/c015ab30-b9ac-40d5-9f41-60d30c45e087)

### Proposed

![Image](https://github.com/user-attachments/assets/36438d6d-5a1a-45ef-91af-7e74c26cc1c9)

![Image](https://github.com/user-attachments/assets/5e54052a-e2e1-4c53-953a-6d33d93a3f13)

### Implementation

Stolen from PyData Sphinx Theme.

```css
.reference.external::after {
  margin-left: 0.3em;
  display: inline-block;
  content: var(--pst-icon-external-link);
  white-space: nowrap;
  font: var(--fa-font-solid);
  font-size: .75em;
}
```

A new file needs to be created at `src/plone_sphinx_theme/assets/styles/abstracts/_links.scss` that contains the style. It also needs to comply with any link styles from https://github.com/pydata/pydata-sphinx-theme/blob/main/src/pydata_sphinx_theme/assets/styles/abstracts/_links.scss.

I also add comments at the top of the SCSS files to say where I get the snippets, why they are present, and any other relevant information for future maintainers. You can see an example in:

https://github.com/plone/plone-sphinx-theme/blob/b3ffc1e6566dc9b6380ce35d9172e07c319bbf2b/src/plone_sphinx_theme/assets/styles/abstracts/_mixins.scss#L1-L6

See also https://plone-sphinx-theme.readthedocs.io/guides/contribute.html#add-or-edit-styles
